services:

  app:
    build: .
    container_name: ai-intrusion-defense
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: ai-intrusion-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: ai-intrusion-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped